language: csharp
dotnet: 3.1
solution: SendGrid.sln
os: linux
dist: bionic
mono: none
services:
- docker
script:
- if [ -n "$DOCKER_PASSWORD" ]; then echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin; fi
- make test-docker
- make release
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push **/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
    --skip-duplicate
  on:
    branch: main
    tags: true
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: SgO1f5k8ZjR9mqUkuQYkkQBoPI23Cwaf8mh2c+usXdDv6CEziZPecKwPM+cUp1yBVRXezjdgo+yLQ+YDvCDdOVRoGcYRUqE6tlD5i28YmfzZMx8Vwsf/B5z3T9c5Ccj+EMnHEn3df+YkLksG8XjZcTXx8MsgWNCxnNZNEh7FXbg=
